version: '2'
services:
  tomcat:
    image: tomcat:latest
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=local"
    build:
      context: .
      dockerfile : Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./hiHelloHome-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    restart: always